### ISSUE TITLE
Atem library adaption

### ISSUE THREAD

**Issue by Dev1an** [iSchluff/atemcontrol#2]
Hi I see you adapted the code from my library. Is there a reason why you copied the code into your own module rather than using the package via NPM?
If you think some things need to be changed in my lib, feel free to fork and file a pull requests. I am happy to merge them into my module.

**Comment by iSchluff** [comment]
It was just for some experiments of running the code on a gen1 raspberry-pi. But I wasn't very successful, nodejs on the pi seems to be too slow to handle the initial packets of the atem for responding in time.

I replaced the code with the npm version.
